import { switzer } from "@/libs/fonts";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rocket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={switzer.className}>
      <Navbar />
      {children}
      </body>
    </html>
  );
}