import { switzer } from "@/libs/fonts";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rocket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${switzer.className}  ${
          process.env.NODE_ENV == "development" ? "debug-screens" : ""
        }`}
      >
        {children}
      </body>
    </html>
  );
}
